[package]

name = "html5ever"
version = "0.0.0"
authors = [ "The html5ever Project Developers" ]

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf"
[dependencies.phf_mac]
git = "https://github.com/sfackler/rust-phf"

[dependencies.string_cache]
git = "https://github.com/servo/string-cache"
[dependencies.string_cache_macros]
git = "https://github.com/servo/string-cache"

[dependencies.html5ever_macros]
path = "macros"

[[test]]
name = "html5ever-external-test"
