[package]

name = "html5ever"
version = "0.2.4"
authors = [ "The html5ever Project Developers" ]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://kmcallister.github.io/docs/html5ever/html5ever/index.html"
build = "build.rs"

[lib]
name = "html5ever"

# https://github.com/rust-lang/cargo/issues/1512
doctest = false

[features]
unstable = ["html5ever_macros", "tendril/unstable", "string_cache/unstable", "string_cache_plugin", "rc/unstable"]

[dependencies]
time = "0"
log = "0"
phf = "0.7"
string_cache = "0.1.12"
string_cache_plugin = { version = "0.1.7", optional = true }
mac = "0"
tendril = "0.1.3"
rc = "0.1.1"

[dev-dependencies]
rustc-serialize = "0.3.15"

[build-dependencies]
phf_codegen = "0.7.3"
rustc-serialize = "0.3.15"
html5ever_macros = { version = "0.2.0", path = "macros", optional = true }

[profile.dev]
debug = false

[profile.test]
debug = false
