[package]

name = "html5ever"
version = "0.1.0"
authors = [ "The html5ever Project Developers" ]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://kmcallister.github.io/docs/html5ever/html5ever/index.html"

[lib]
name = "html5ever"

# https://github.com/rust-lang/cargo/issues/1512
doctest = false

[dependencies]
time = "0"
log = "0"
phf = "0.7"
phf_macros = "0.7"
string_cache = "0"
string_cache_plugin = "0"
mac = "0"
[dependencies.tendril]
git = "https://github.com/kmcallister/tendril"


[dependencies.html5ever_macros]
version = "0.1.0"
path = "macros"

[dev-dependencies]
rustc-serialize = "0"

[dev-dependencies.html5ever_test_util]
version = "0.1.0"
path = "test_util"

[profile.dev]
debug = false

[profile.test]
debug = false
