[package]

name = "html5ever"
version = "0.0.0"
authors = [ "The html5ever Project Developers" ]

[dependencies]
phf = "0"
phf_mac = "0"
time = "0"
iobuf = "3"

[dependencies.string_cache]
git = "https://github.com/servo/string-cache"
[dependencies.string_cache_macros]
git = "https://github.com/servo/string-cache"

[dependencies.html5ever_macros]
path = "macros"

[[test]]
name = "html5ever-external-test"

[profile.release]

opt-level = 3
debug = false
rpath = false
lto = false
