[package]

name = "xml5ever"
version = "0.12.0"
authors = ["The xml5ever project developers"]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "Push based streaming parser for xml"
documentation = "https://docs.rs/xml5ever/"

homepage = "https://github.com/servo/html5ever/blob/master/xml5ever/README.md"
readme = "README.md"
keywords = ["xml", "xml5", "parser", "parsing"]
exclude = ["xml5lib-tests/*"]
categories = [ "parser-implementations", "web-programming" ]

[lib]
name = "xml5ever"

doctest = true

[dependencies]
time = "0.1"
log = "0.3"
mac = "0.1"
markup5ever = {version = "0.7", path = "../markup5ever" }

[dev-dependencies]
rustc-serialize = "0.3.15"
rustc-test = "0.2"
